services/app/beer/urls.py
from django.conf.urls import url
from beer import views


app_name = 'beer'
urlpatterns = [
    url(r'beer/(?P<pk>\d+)$', views.BeerUpdateDeleteView.as_view(), name='detail'),
    url(r'beer/$', views.BeerListView.as_view(), name='list'),
    url(r'beer/create$', views.BeerCreateView.as_view(), name='create'),
    url(r'beer/edit$', views.BeerUpdateDeleteView.as_view(), name='edit'),
]

services/app/pivo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beer.urls')),
]

services/app/beer/models.py
from django.db import models


class Manufacturer(models.Model):
    name = models.CharField(max_length=255)


class Beer(models.Model):
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, null=True, blank=False)
    name = models.CharField(max_length=255, null=False, blank=False)
    image = models.ImageField(upload_to='uploads/', null=True, blank=False)

services/app/beer/views.py
from django.shortcuts import redirect
from rest_framework.reverse import reverse
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer

from beer import serializers
from beer.models import Beer
from beer.tasks import add_beer_image_task


class BeerUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = serializers.BeerSerializer
    template_name = 'beer_form.html'
    renderer_classes = [TemplateHTMLRenderer]

    def get_queryset(self):
        return Beer.objects.all()

    def get(self, *args, **kwargs):
        return Response()

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        return redirect(reverse('beer:list'))

    def update(self, request, *args, **kwargs):
        super().update(request, *args, **kwargs)
        return redirect(reverse('beer:list', request=request))


class BeerListView(generics.CreateAPIView):
    serializer_class = serializers.BeerSerializer
    template_name = 'beer_list.html'
    renderer_classes = [TemplateHTMLRenderer]

    def get_queryset(self):
        return Beer.objects.all()

    def get(self, *args, **kwargs):
        return Response({'beers': self.get_queryset()})


class BeerCreateView(generics.CreateAPIView):
    template_name = 'beer_form.html'
    serializer_class = serializers.BeerSerializer
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, *args, **kwargs):
        return Response({})

    def create(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            serializer.save()
            add_beer_image_task.delay(serializer.instance.pk)

        return redirect(reverse('beer:list'))

services/app/beer/templates/beer_detail.html
{% extends 'layout.html' %}
{% block content %}
<p>This is {{ beer.name }}</p>
{% endblock %}

services/app/beer/templates/beer_form.html
{% extends 'layout.html' %}
{% block content %}
<form method="post" action="{% url 'beer:create' %}">
  {% csrf_token %}
  <input type="text" name="name">
  <label for="name">Name</label>
  <input type="submit" value="Create">
</form>
{% endblock %}

services/app/beer/templates/beer_list.html
{% extends 'layout.html' %}
{% block content %}
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
    </tr>
  </thead>
  {% for beer in beers %}
  <tr>
    <td>{{ beer.id }}</td>
    <td>{{ beer.name }}</td>
    <td>{% url 'beer:edit' %}</td>
  </tr>
  {% endfor %}
</table>
<br>
<a href="{% url 'beer:create' %}">Create beer</a>
{% endblock %}

services/app/beer/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>Beer app</title>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>